---

sudo: required

dist: trusty

language: python

python:
  - 2.7

services:
  - docker

before_install:
  - pip install --upgrade --upgrade-strategy only-if-needed ansible docker-py docker-compose
  - pip install --upgrade --upgrade-strategy only-if-needed ansible-container[docker]

install:
  - pip install -r ansible-requirements.txt
  - ansible-galaxy install -r requirements.yml

script:
  - yamllint -c .yamllint .
  - ansible-container build --use-local-python -- --diff --verbose
  - ansible-container run
  - docker ps -a
  - docker images
  - ansible-container stop --force
  - ansible-container destroy
