---

sudo: required

dist: trusty

language: python

python:
  - 2.7

services:
  - docker

env:
  global:
    - ANSIBLE_FORCE_COLOR: true
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'

before_install:
  - pip install --upgrade git+git://github.com/ansible/ansible.git@stable-2.4
  - pip install --upgrade docker docker-compose
  - pip install --upgrade ansible-container[docker,k8s]

install:
  - pip install -r ansible-requirements.txt
  - ansible-galaxy install -r requirements.yml

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker version
  - docker-compose version
  - docker info
  - yamllint -c .yamllint .
  - ansible-container build --use-local-python -- --diff --verbose
  - ansible-container run
  - docker ps -a
  - docker images
  - ansible-container stop --force

after_success:
  - |
    if [ ! -z ${TRAVIS_TAG+x} ]; then
      read -a v <<< $(echo ${TRAVIS_TAG} | sed 's/[\.\-]/ /g')
      ansible-container push --push-to docker --tag ${v[0]}.${v[1]}.${v[2]}-${v[3]}
      ansible-container push --push-to docker --tag ${v[0]}.${v[1]}.${v[2]}
      ansible-container push --push-to docker --tag ${v[0]}.${v[1]}
      ansible-container push --push-to docker --tag ${v[0]}
      ansible-container push --push-to docker
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
